import { theme as antTheme, type ThemeConfig } from "antd";

export type AppThemeMode =
  | "light"
  | "dark"
  | "forge"
  | "forge-light"
  | "github"
  | "github-light"
  | "verft-light"
  | "verft-dark"
  | "ember-light"
  | "ember-dark"
  | "moss-light"
  | "moss-dark"
  | "graphite-light"
  | "graphite-dark";

const sharedComponents: ThemeConfig["components"] = {
  Button: {
    fontWeight: 600,
    defaultShadow: "none",
    primaryShadow: "none",
    dangerShadow: "none"
  },
  Card: {
    bodyPadding: 16,
    headerPadding: 16
  },
  Timeline: {
    dotBorderWidth: 2
  }
};

export const lightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#1C8057",
    colorSuccess: "#3A8F63",
    colorWarning: "#E6B85C",
    colorError: "#C95C5C",
    colorInfo: "#6B8FA3",
    colorTextBase: "#444E39",
    colorBgBase: "#FBFDFC",
    colorPrimaryBg: "#ECF2EC",
    colorPrimaryBgHover: "#D1E4D6",
    colorPrimaryBorder: "#B6C5BA",
    colorPrimaryBorderHover: "#1C8057",
    colorPrimaryHover: "#166746",
    colorPrimaryActive: "#0F4F35",
    colorPrimaryText: "#1C8057",
    colorPrimaryTextHover: "#166746",
    colorPrimaryTextActive: "#0F4F35",
    colorSuccessBg: "#E8F3EA",
    colorSuccessBgHover: "#D1E4D6",
    colorSuccessBorder: "#B6C5BA",
    colorSuccessBorderHover: "#3A8F63",
    colorSuccessHover: "#2D7A4F",
    colorSuccessActive: "#1F6340",
    colorSuccessText: "#3A8F63",
    colorSuccessTextHover: "#2D7A4F",
    colorSuccessTextActive: "#1F6340",
    colorWarningBg: "#F9F3E6",
    colorWarningBgHover: "#F2E6C7",
    colorWarningBorder: "#E6D1A3",
    colorWarningBorderHover: "#E6B85C",
    colorWarningHover: "#D4A853",
    colorWarningActive: "#C2964A",
    colorWarningText: "#E6B85C",
    colorWarningTextHover: "#D4A853",
    colorWarningTextActive: "#C2964A",
    colorErrorBg: "#F7E6E6",
    colorErrorBgHover: "#ECD1D1",
    colorErrorBorder: "#E0B8B8",
    colorErrorBorderHover: "#C95C5C",
    colorErrorHover: "#B85353",
    colorErrorActive: "#A14747",
    colorErrorText: "#C95C5C",
    colorErrorTextHover: "#B85353",
    colorErrorTextActive: "#A14747",
    colorInfoBg: "#E8EDF0",
    colorInfoBgHover: "#D1DEE5",
    colorInfoBorder: "#B6C5BA",
    colorInfoBorderHover: "#6B8FA3",
    colorInfoHover: "#5A7D92",
    colorInfoActive: "#4B6B7E",
    colorInfoText: "#6B8FA3",
    colorInfoTextHover: "#5A7D92",
    colorInfoTextActive: "#4B6B7E",
    colorText: "#5A675D",
    colorTextSecondary: "#889C85",
    colorTextTertiary: "#A8B8A5",
    colorTextQuaternary: "#C9D4CC",
    colorTextDisabled: "#C9D4CC",
    colorTextPlaceholder: "#889C85",
    colorBgContainer: "#FFFFFF",
    colorBgElevated: "#FFFFFF",
    colorBgLayout: "#F4F8F5",
    colorBgSpotlight: "rgba(68, 78, 57, 0.85)",
    colorBgMask: "rgba(68, 78, 57, 0.45)",
    colorBorder: "#D1DED3",
    colorBorderSecondary: "#E8ECE9",
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 2px 8px 0 rgba(28, 39, 32, 0.08)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#FFFFFF",
      defaultColor: "#5A675D",
      defaultBorderColor: "#D1DED3",
      defaultHoverBg: "#FFFFFF",
      defaultHoverColor: "#166746",
      defaultHoverBorderColor: "#1C8057",
      defaultActiveBg: "#FFFFFF",
      defaultActiveColor: "#0F4F35",
      defaultActiveBorderColor: "#0F4F35"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#FFFFFF",
      extraColor: "#889C85"
    },
    Input: {
      hoverBorderColor: "#1C8057",
      activeBorderColor: "#1C8057",
      activeShadow: "0 0 0 1px rgba(28, 128, 87, 0.20)",
      hoverBg: "#FFFFFF",
      activeBg: "#FFFFFF"
    },
    Tag: {
      defaultBg: "#ECF2EC",
      defaultColor: "#1C8057"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#1C8057",
      tailColor: "#D1DED3"
    },
    Progress: {
      defaultColor: "#1C8057",
      remainingColor: "#E8ECE9"
    }
  }
};

export const darkAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#67C496",
    colorSuccess: "#6AC28F",
    colorWarning: "#E1B458",
    colorError: "#D46C6C",
    colorInfo: "#89AEC3",
    colorTextBase: "#E2ECE3",
    colorBgBase: "#101613",
    colorPrimaryBg: "#163A29",
    colorPrimaryBgHover: "#1C4A34",
    colorPrimaryBorder: "#27543E",
    colorPrimaryBorderHover: "#67C496",
    colorPrimaryHover: "#7AD1A5",
    colorPrimaryActive: "#4CA87A",
    colorPrimaryText: "#8BE0AE",
    colorPrimaryTextHover: "#A0E7BF",
    colorPrimaryTextActive: "#67C496",
    colorSuccessBg: "#153523",
    colorSuccessBgHover: "#1B442E",
    colorSuccessBorder: "#27543E",
    colorSuccessBorderHover: "#6AC28F",
    colorSuccessHover: "#82D3A5",
    colorSuccessActive: "#58AF7E",
    colorSuccessText: "#8BE0AE",
    colorSuccessTextHover: "#A0E7BF",
    colorSuccessTextActive: "#67C496",
    colorWarningBg: "#352B17",
    colorWarningBgHover: "#45371D",
    colorWarningBorder: "#5B4823",
    colorWarningBorderHover: "#E1B458",
    colorWarningHover: "#ECC46F",
    colorWarningActive: "#C89A3F",
    colorWarningText: "#F0C97B",
    colorWarningTextHover: "#F5D591",
    colorWarningTextActive: "#E1B458",
    colorErrorBg: "#3A1F1F",
    colorErrorBgHover: "#482626",
    colorErrorBorder: "#613131",
    colorErrorBorderHover: "#D46C6C",
    colorErrorHover: "#DF8383",
    colorErrorActive: "#BE5D5D",
    colorErrorText: "#E79999",
    colorErrorTextHover: "#F0AEAE",
    colorErrorTextActive: "#D46C6C",
    colorInfoBg: "#162730",
    colorInfoBgHover: "#1C3340",
    colorInfoBorder: "#244353",
    colorInfoBorderHover: "#89AEC3",
    colorInfoHover: "#9ABDD0",
    colorInfoActive: "#7095AA",
    colorInfoText: "#A7C6D7",
    colorInfoTextHover: "#BAD6E4",
    colorInfoTextActive: "#89AEC3",
    colorText: "#D8E2D9",
    colorTextSecondary: "#9AAFA0",
    colorTextTertiary: "#7E9486",
    colorTextQuaternary: "#61786A",
    colorTextDisabled: "#61786A",
    colorTextPlaceholder: "#8AA092",
    colorBgContainer: "#171F1B",
    colorBgElevated: "#1B2520",
    colorBgLayout: "#0E1411",
    colorBgSpotlight: "rgba(13, 20, 17, 0.92)",
    colorBgMask: "rgba(0, 0, 0, 0.55)",
    colorBorder: "#2A3931",
    colorBorderSecondary: "#213028",
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 8px 24px rgba(0, 0, 0, 0.28)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#171F1B",
      defaultColor: "#D8E2D9",
      defaultBorderColor: "#2A3931",
      defaultHoverBg: "#1D2722",
      defaultHoverColor: "#8BE0AE",
      defaultHoverBorderColor: "#67C496",
      defaultActiveBg: "#141C18",
      defaultActiveColor: "#67C496",
      defaultActiveBorderColor: "#4CA87A"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#171F1B",
      extraColor: "#9AAFA0"
    },
    Input: {
      hoverBorderColor: "#67C496",
      activeBorderColor: "#67C496",
      activeShadow: "0 0 0 1px rgba(103, 196, 150, 0.24)",
      hoverBg: "#101613",
      activeBg: "#101613"
    },
    Tag: {
      defaultBg: "#173424",
      defaultColor: "#8BE0AE"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#67C496",
      tailColor: "#2A3931"
    },
    Progress: {
      defaultColor: "#67C496",
      remainingColor: "#2A3931"
    }
  }
};

export const forgeAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#ff6b35",
    colorSuccess: "#00c2a9",
    colorWarning: "#ffa726",
    colorError: "#ff5252",
    colorInfo: "#5e72eb",
    colorTextBase: "#c9d1d9",
    colorBgBase: "#0d1117",
    colorPrimaryBg: "#ff6b3520",
    colorPrimaryBgHover: "#ff6b3530",
    colorPrimaryBorder: "#ff6b3550",
    colorPrimaryBorderHover: "#ff6b3570",
    colorPrimaryHover: "#ff8257",
    colorPrimaryActive: "#e55929",
    colorPrimaryText: "#ff6b35",
    colorPrimaryTextHover: "#ff8257",
    colorPrimaryTextActive: "#e55929",
    colorInfoBg: "#5e72eb20",
    colorInfoBgHover: "#5e72eb30",
    colorInfoBorder: "#5e72eb50",
    colorInfoBorderHover: "#5e72eb70",
    colorInfoHover: "#7c8ff0",
    colorInfoActive: "#4c5fd6",
    colorInfoText: "#5e72eb",
    colorInfoTextHover: "#7c8ff0",
    colorInfoTextActive: "#4c5fd6",
    colorText: "rgba(201, 209, 217, 0.88)",
    colorTextSecondary: "rgba(201, 209, 217, 0.65)",
    colorTextTertiary: "rgba(201, 209, 217, 0.45)",
    colorTextQuaternary: "rgba(201, 209, 217, 0.25)",
    colorTextDisabled: "rgba(201, 209, 217, 0.25)",
    colorTextPlaceholder: "rgba(201, 209, 217, 0.42)",
    colorBgContainer: "#161b22",
    colorBgElevated: "#21262d",
    colorBgLayout: "#0d1117",
    colorBgSpotlight: "rgba(201, 209, 217, 0.85)",
    colorBgMask: "rgba(0, 0, 0, 0.6)",
    colorBorder: "#30363d",
    colorBorderSecondary: "#21262d",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "0 2px 8px 0 rgba(0, 0, 0, 0.4)",
    boxShadowSecondary: "0 4px 12px 0 rgba(0, 0, 0, 0.5)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#161b22",
      defaultColor: "rgba(201, 209, 217, 0.88)",
      defaultBorderColor: "#30363d",
      defaultHoverBg: "#21262d",
      defaultHoverColor: "#ff8257",
      defaultHoverBorderColor: "#ff6b3570",
      defaultActiveBg: "#161b22",
      defaultActiveColor: "#e55929",
      defaultActiveBorderColor: "#e55929"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#161b22",
      extraColor: "rgba(201, 209, 217, 0.65)"
    },
    Input: {
      hoverBorderColor: "#ff6b3570",
      activeBorderColor: "#ff6b35",
      activeShadow: "0 0 0 1px rgba(255, 107, 53, 0.24)",
      hoverBg: "#0d1117",
      activeBg: "#0d1117"
    },
    Tag: {
      defaultBg: "#ff6b3520",
      defaultColor: "#ff6b35"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#ff6b35",
      tailColor: "#30363d"
    },
    Progress: {
      defaultColor: "#ff6b35",
      remainingColor: "#30363d"
    }
  }
};

export const forgeLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#ff6b35",
    colorSuccess: "#0f9d85",
    colorWarning: "#d97706",
    colorError: "#dc2626",
    colorInfo: "#4f6df5",
    colorTextBase: "#332821",
    colorBgBase: "#fff8f3",
    colorPrimaryBg: "#fff0e8",
    colorPrimaryBgHover: "#ffe1d4",
    colorPrimaryBorder: "#ffc0a5",
    colorPrimaryBorderHover: "#ff946b",
    colorPrimaryHover: "#f97341",
    colorPrimaryActive: "#e55b2a",
    colorPrimaryText: "#d95a2c",
    colorPrimaryTextHover: "#f97341",
    colorPrimaryTextActive: "#b94820",
    colorSuccessBg: "#e7f7f3",
    colorSuccessBgHover: "#ccefe7",
    colorSuccessBorder: "#93d8c8",
    colorSuccessBorderHover: "#0f9d85",
    colorSuccessHover: "#14b39a",
    colorSuccessActive: "#0b7c69",
    colorSuccessText: "#0f9d85",
    colorSuccessTextHover: "#14b39a",
    colorSuccessTextActive: "#0b7c69",
    colorWarningBg: "#fff4db",
    colorWarningBgHover: "#ffe7b0",
    colorWarningBorder: "#f6c978",
    colorWarningBorderHover: "#d97706",
    colorWarningHover: "#ea8b17",
    colorWarningActive: "#b95f05",
    colorWarningText: "#b96b00",
    colorWarningTextHover: "#d97706",
    colorWarningTextActive: "#9a5600",
    colorErrorBg: "#fff0ef",
    colorErrorBgHover: "#ffd9d6",
    colorErrorBorder: "#ffb0aa",
    colorErrorBorderHover: "#dc2626",
    colorErrorHover: "#ef4444",
    colorErrorActive: "#b91c1c",
    colorErrorText: "#dc2626",
    colorErrorTextHover: "#ef4444",
    colorErrorTextActive: "#b91c1c",
    colorInfoBg: "#eef1ff",
    colorInfoBgHover: "#dfe4ff",
    colorInfoBorder: "#c0cbff",
    colorInfoBorderHover: "#4f6df5",
    colorInfoHover: "#6f86ff",
    colorInfoActive: "#3e57d0",
    colorInfoText: "#4f6df5",
    colorInfoTextHover: "#6f86ff",
    colorInfoTextActive: "#3e57d0",
    colorText: "rgba(51, 40, 33, 0.92)",
    colorTextSecondary: "rgba(51, 40, 33, 0.68)",
    colorTextTertiary: "rgba(51, 40, 33, 0.5)",
    colorTextQuaternary: "rgba(51, 40, 33, 0.34)",
    colorTextDisabled: "rgba(51, 40, 33, 0.34)",
    colorTextPlaceholder: "rgba(51, 40, 33, 0.46)",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#fffaf6",
    colorBgLayout: "#fff3eb",
    colorBgSpotlight: "rgba(51, 40, 33, 0.86)",
    colorBgMask: "rgba(91, 60, 45, 0.22)",
    colorBorder: "#e7d8cd",
    colorBorderSecondary: "#f2e8e1",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "0 2px 8px 0 rgba(120, 73, 45, 0.10)",
    boxShadowSecondary: "0 8px 24px 0 rgba(120, 73, 45, 0.16)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#ffffff",
      defaultColor: "rgba(51, 40, 33, 0.92)",
      defaultBorderColor: "#e7d8cd",
      defaultHoverBg: "#fff8f3",
      defaultHoverColor: "#f97341",
      defaultHoverBorderColor: "#ff946b",
      defaultActiveBg: "#ffffff",
      defaultActiveColor: "#d95a2c",
      defaultActiveBorderColor: "#d95a2c"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#ffffff",
      extraColor: "rgba(51, 40, 33, 0.68)"
    },
    Input: {
      hoverBorderColor: "#ff946b",
      activeBorderColor: "#ff6b35",
      activeShadow: "0 0 0 1px rgba(255, 107, 53, 0.22)",
      hoverBg: "#ffffff",
      activeBg: "#ffffff"
    },
    Tag: {
      defaultBg: "#fff0e8",
      defaultColor: "#d95a2c"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#ff6b35",
      tailColor: "#e7d8cd"
    },
    Progress: {
      defaultColor: "#ff6b35",
      remainingColor: "#f2e8e1"
    }
  }
};

export const githubAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#1f6feb",
    colorSuccess: "#238636",
    colorWarning: "#f85149",
    colorError: "#f85149",
    colorInfo: "#1f6feb",
    colorTextBase: "#c9d1d9",
    colorBgBase: "#0d1117",
    colorPrimaryBg: "#21262d",
    colorPrimaryBgHover: "#30363d",
    colorPrimaryBorder: "#1f6feb",
    colorPrimaryBorderHover: "#388bfd",
    colorPrimaryHover: "#388bfd",
    colorPrimaryActive: "#1f6feb",
    colorPrimaryText: "#58a6ff",
    colorPrimaryTextHover: "#79c0ff",
    colorPrimaryTextActive: "#a5d6ff",
    colorSuccessBg: "#21262d",
    colorSuccessBgHover: "#30363d",
    colorSuccessBorder: "#238636",
    colorSuccessBorderHover: "#2ea043",
    colorSuccessHover: "#2ea043",
    colorSuccessActive: "#238636",
    colorSuccessText: "#3fb950",
    colorSuccessTextHover: "#56d364",
    colorSuccessTextActive: "#7ee787",
    colorWarningBg: "#21262d",
    colorWarningBgHover: "#30363d",
    colorWarningBorder: "#f85149",
    colorWarningBorderHover: "#ff7b72",
    colorWarningHover: "#ff7b72",
    colorWarningActive: "#f85149",
    colorWarningText: "#ff7b72",
    colorWarningTextHover: "#ffa198",
    colorWarningTextActive: "#ffc1ba",
    colorErrorBg: "#21262d",
    colorErrorBgHover: "#30363d",
    colorErrorBorder: "#f85149",
    colorErrorBorderHover: "#ff7b72",
    colorErrorHover: "#ff7b72",
    colorErrorActive: "#f85149",
    colorErrorText: "#ff7b72",
    colorErrorTextHover: "#ffa198",
    colorErrorTextActive: "#ffc1ba",
    colorInfoBg: "#21262d",
    colorInfoBgHover: "#30363d",
    colorInfoBorder: "#1f6feb",
    colorInfoBorderHover: "#388bfd",
    colorInfoHover: "#388bfd",
    colorInfoActive: "#1f6feb",
    colorInfoText: "#58a6ff",
    colorInfoTextHover: "#79c0ff",
    colorInfoTextActive: "#a5d6ff",
    colorText: "#c9d1d9",
    colorTextSecondary: "#8b949e",
    colorTextTertiary: "#6e7681",
    colorTextQuaternary: "#484f58",
    colorTextDisabled: "#484f58",
    colorTextPlaceholder: "#6e7681",
    colorBgContainer: "#161b22",
    colorBgElevated: "#21262d",
    colorBgLayout: "#0d1117",
    colorBgSpotlight: "#21262d",
    colorBgMask: "rgba(13, 17, 23, 0.6)",
    colorBorder: "#30363d",
    colorBorderSecondary: "#21262d",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: "0 0 0 1px #30363d",
    boxShadowSecondary: "0 8px 24px rgba(1, 4, 9, 0.48)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#161b22",
      defaultColor: "#c9d1d9",
      defaultBorderColor: "#30363d",
      defaultHoverBg: "#21262d",
      defaultHoverColor: "#79c0ff",
      defaultHoverBorderColor: "#388bfd",
      defaultActiveBg: "#161b22",
      defaultActiveColor: "#58a6ff",
      defaultActiveBorderColor: "#1f6feb"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#161b22",
      extraColor: "#8b949e"
    },
    Input: {
      hoverBorderColor: "#388bfd",
      activeBorderColor: "#1f6feb",
      activeShadow: "0 0 0 1px rgba(31, 111, 235, 0.28)",
      hoverBg: "#0d1117",
      activeBg: "#0d1117"
    },
    Tag: {
      defaultBg: "#21262d",
      defaultColor: "#58a6ff"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#1f6feb",
      tailColor: "#30363d"
    },
    Progress: {
      defaultColor: "#1f6feb",
      remainingColor: "#30363d"
    }
  }
};

export const githubLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#0969da",
    colorSuccess: "#1a7f37",
    colorWarning: "#bf8700",
    colorError: "#cf222e",
    colorInfo: "#0969da",
    colorTextBase: "#1f2328",
    colorBgBase: "#ffffff",
    colorPrimaryBg: "#ddf4ff",
    colorPrimaryBgHover: "#b6e3ff",
    colorPrimaryBorder: "#80ccff",
    colorPrimaryBorderHover: "#54aeff",
    colorPrimaryHover: "#218bff",
    colorPrimaryActive: "#0969da",
    colorPrimaryText: "#0969da",
    colorPrimaryTextHover: "#218bff",
    colorPrimaryTextActive: "#0550ae",
    colorSuccessBg: "#dafbe1",
    colorSuccessBgHover: "#aceebb",
    colorSuccessBorder: "#4ac26b",
    colorSuccessBorderHover: "#2da44e",
    colorSuccessHover: "#2da44e",
    colorSuccessActive: "#1a7f37",
    colorSuccessText: "#1a7f37",
    colorSuccessTextHover: "#2da44e",
    colorSuccessTextActive: "#116329",
    colorWarningBg: "#fff8c5",
    colorWarningBgHover: "#fae17d",
    colorWarningBorder: "#d4a72c",
    colorWarningBorderHover: "#bf8700",
    colorWarningHover: "#9a6700",
    colorWarningActive: "#7d4e00",
    colorWarningText: "#9a6700",
    colorWarningTextHover: "#bf8700",
    colorWarningTextActive: "#7d4e00",
    colorErrorBg: "#ffebe9",
    colorErrorBgHover: "#ffcecb",
    colorErrorBorder: "#ff8182",
    colorErrorBorderHover: "#cf222e",
    colorErrorHover: "#cf222e",
    colorErrorActive: "#a40e26",
    colorErrorText: "#cf222e",
    colorErrorTextHover: "#a40e26",
    colorErrorTextActive: "#82071e",
    colorInfoBg: "#ddf4ff",
    colorInfoBgHover: "#b6e3ff",
    colorInfoBorder: "#80ccff",
    colorInfoBorderHover: "#54aeff",
    colorInfoHover: "#218bff",
    colorInfoActive: "#0969da",
    colorInfoText: "#0969da",
    colorInfoTextHover: "#218bff",
    colorInfoTextActive: "#0550ae",
    colorText: "#1f2328",
    colorTextSecondary: "#57606a",
    colorTextTertiary: "#6e7781",
    colorTextQuaternary: "#8c959f",
    colorTextDisabled: "#8c959f",
    colorTextPlaceholder: "#6e7781",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#f6f8fa",
    colorBgSpotlight: "rgba(31, 35, 40, 0.85)",
    colorBgMask: "rgba(140, 149, 159, 0.2)",
    colorBorder: "#d0d7de",
    colorBorderSecondary: "#eaeef2",
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: "0 1px 3px rgba(31, 35, 40, 0.12)",
    boxShadowSecondary: "0 8px 24px rgba(140, 149, 159, 0.2)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#ffffff",
      defaultColor: "#1f2328",
      defaultBorderColor: "#d0d7de",
      defaultHoverBg: "#f6f8fa",
      defaultHoverColor: "#0969da",
      defaultHoverBorderColor: "#0969da",
      defaultActiveBg: "#ffffff",
      defaultActiveColor: "#0550ae",
      defaultActiveBorderColor: "#0550ae"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#ffffff",
      extraColor: "#57606a"
    },
    Input: {
      hoverBorderColor: "#0969da",
      activeBorderColor: "#0969da",
      activeShadow: "0 0 0 1px rgba(9, 105, 218, 0.3)",
      hoverBg: "#ffffff",
      activeBg: "#ffffff"
    },
    Tag: {
      defaultBg: "#ddf4ff",
      defaultColor: "#0969da"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#0969da",
      tailColor: "#d0d7de"
    },
    Progress: {
      defaultColor: "#0969da",
      remainingColor: "#eaeef2"
    }
  }
};

export const verftLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#1A7A9B",
    colorSuccess: "#2E8B57",
    colorWarning: "#C8922A",
    colorError: "#C0392B",
    colorInfo: "#4A7FB5",
    colorTextBase: "#1C2E40",
    colorBgBase: "#F5F2E8",
    colorPrimaryBg: "#E8F4F8",
    colorPrimaryBgHover: "#CCE8F2",
    colorPrimaryBorder: "#9CCEDD",
    colorPrimaryBorderHover: "#1A7A9B",
    colorPrimaryHover: "#156884",
    colorPrimaryActive: "#105E77",
    colorPrimaryText: "#1A7A9B",
    colorPrimaryTextHover: "#156884",
    colorPrimaryTextActive: "#105E77",
    colorSuccessBg: "#E8F5EE",
    colorSuccessBgHover: "#CCEAD9",
    colorSuccessBorder: "#9ECFB4",
    colorSuccessBorderHover: "#2E8B57",
    colorSuccessHover: "#267849",
    colorSuccessActive: "#1D5F3A",
    colorSuccessText: "#2E8B57",
    colorSuccessTextHover: "#267849",
    colorSuccessTextActive: "#1D5F3A",
    colorWarningBg: "#FAF3E0",
    colorWarningBgHover: "#F2E3B8",
    colorWarningBorder: "#E0C570",
    colorWarningBorderHover: "#C8922A",
    colorWarningHover: "#B47F22",
    colorWarningActive: "#9E6E1A",
    colorWarningText: "#C8922A",
    colorWarningTextHover: "#B47F22",
    colorWarningTextActive: "#9E6E1A",
    colorErrorBg: "#FAE8E6",
    colorErrorBgHover: "#F2CFCC",
    colorErrorBorder: "#E0A8A5",
    colorErrorBorderHover: "#C0392B",
    colorErrorHover: "#A63222",
    colorErrorActive: "#8C2A1D",
    colorErrorText: "#C0392B",
    colorErrorTextHover: "#A63222",
    colorErrorTextActive: "#8C2A1D",
    colorInfoBg: "#E8EFF8",
    colorInfoBgHover: "#CCDEEF",
    colorInfoBorder: "#99BDE0",
    colorInfoBorderHover: "#4A7FB5",
    colorInfoHover: "#3E6D9C",
    colorInfoActive: "#315980",
    colorInfoText: "#4A7FB5",
    colorInfoTextHover: "#3E6D9C",
    colorInfoTextActive: "#315980",
    colorText: "#2C4258",
    colorTextSecondary: "#5A7A96",
    colorTextTertiary: "#8AA5BE",
    colorTextQuaternary: "#C0D5E5",
    colorTextDisabled: "#C0D5E5",
    colorTextPlaceholder: "#7A9AB5",
    colorBgContainer: "#FFFFFF",
    colorBgElevated: "#FDFAF4",
    colorBgLayout: "#EEF6F8",
    colorBgSpotlight: "rgba(28, 46, 64, 0.85)",
    colorBgMask: "rgba(28, 46, 64, 0.45)",
    colorBorder: "#C8DBE5",
    colorBorderSecondary: "#E0ECF2",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 2px 8px 0 rgba(26, 122, 155, 0.10)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#FFFFFF",
      defaultColor: "#2C4258",
      defaultBorderColor: "#C8DBE5",
      defaultHoverBg: "#F5FAFB",
      defaultHoverColor: "#156884",
      defaultHoverBorderColor: "#1A7A9B",
      defaultActiveBg: "#FFFFFF",
      defaultActiveColor: "#105E77",
      defaultActiveBorderColor: "#105E77"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#FFFFFF",
      extraColor: "#5A7A96"
    },
    Input: {
      hoverBorderColor: "#1A7A9B",
      activeBorderColor: "#1A7A9B",
      activeShadow: "0 0 0 1px rgba(26, 122, 155, 0.20)",
      hoverBg: "#FFFFFF",
      activeBg: "#FFFFFF"
    },
    Tag: {
      defaultBg: "#E8F4F8",
      defaultColor: "#1A7A9B"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#1A7A9B",
      tailColor: "#C8DBE5"
    },
    Progress: {
      defaultColor: "#1A7A9B",
      remainingColor: "#E0ECF2"
    }
  }
};

export const verftDarkAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#D4A84B",
    colorSuccess: "#4DAA6A",
    colorWarning: "#E8C56B",
    colorError: "#D46060",
    colorInfo: "#6BAED6",
    colorTextBase: "#E8F4F8",
    colorBgBase: "#0C1822",
    colorPrimaryBg: "#2A1E08",
    colorPrimaryBgHover: "#3A2A0E",
    colorPrimaryBorder: "#5A4018",
    colorPrimaryBorderHover: "#D4A84B",
    colorPrimaryHover: "#E0B85C",
    colorPrimaryActive: "#B88E38",
    colorPrimaryText: "#E8C56B",
    colorPrimaryTextHover: "#F0D47E",
    colorPrimaryTextActive: "#D4A84B",
    colorSuccessBg: "#0E2418",
    colorSuccessBgHover: "#132E20",
    colorSuccessBorder: "#1F4D30",
    colorSuccessBorderHover: "#4DAA6A",
    colorSuccessHover: "#5FBF7C",
    colorSuccessActive: "#3D8F56",
    colorSuccessText: "#72CC90",
    colorSuccessTextHover: "#8AD9A6",
    colorSuccessTextActive: "#4DAA6A",
    colorWarningBg: "#251C06",
    colorWarningBgHover: "#342608",
    colorWarningBorder: "#4E3A0E",
    colorWarningBorderHover: "#E8C56B",
    colorWarningHover: "#F0D07A",
    colorWarningActive: "#C8A846",
    colorWarningText: "#F4D890",
    colorWarningTextHover: "#F8E3A4",
    colorWarningTextActive: "#E8C56B",
    colorErrorBg: "#281214",
    colorErrorBgHover: "#351818",
    colorErrorBorder: "#522020",
    colorErrorBorderHover: "#D46060",
    colorErrorHover: "#E07878",
    colorErrorActive: "#BC4E4E",
    colorErrorText: "#E89090",
    colorErrorTextHover: "#F0A4A4",
    colorErrorTextActive: "#D46060",
    colorInfoBg: "#0E1E2E",
    colorInfoBgHover: "#14273C",
    colorInfoBorder: "#1E3D58",
    colorInfoBorderHover: "#6BAED6",
    colorInfoHover: "#7DC0E6",
    colorInfoActive: "#569BC0",
    colorInfoText: "#95CCE8",
    colorInfoTextHover: "#A8D9F0",
    colorInfoTextActive: "#6BAED6",
    colorText: "#D8EEF4",
    colorTextSecondary: "#88AABF",
    colorTextTertiary: "#6A8EA6",
    colorTextQuaternary: "#4E6E85",
    colorTextDisabled: "#4E6E85",
    colorTextPlaceholder: "#7A9EB8",
    colorBgContainer: "#121E2A",
    colorBgElevated: "#172430",
    colorBgLayout: "#0A1520",
    colorBgSpotlight: "rgba(8, 18, 28, 0.92)",
    colorBgMask: "rgba(0, 0, 0, 0.60)",
    colorBorder: "#1E3448",
    colorBorderSecondary: "#162A3C",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 8px 24px rgba(0, 0, 0, 0.40)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#121E2A",
      defaultColor: "#D8EEF4",
      defaultBorderColor: "#1E3448",
      defaultHoverBg: "#18273A",
      defaultHoverColor: "#E8C56B",
      defaultHoverBorderColor: "#D4A84B",
      defaultActiveBg: "#0F1A24",
      defaultActiveColor: "#D4A84B",
      defaultActiveBorderColor: "#B88E38"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#121E2A",
      extraColor: "#88AABF"
    },
    Input: {
      hoverBorderColor: "#D4A84B",
      activeBorderColor: "#D4A84B",
      activeShadow: "0 0 0 1px rgba(212, 168, 75, 0.24)",
      hoverBg: "#0C1822",
      activeBg: "#0C1822"
    },
    Tag: {
      defaultBg: "#2A1E08",
      defaultColor: "#E8C56B"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#D4A84B",
      tailColor: "#1E3448"
    },
    Progress: {
      defaultColor: "#D4A84B",
      remainingColor: "#1E3448"
    }
  }
};

export const emberLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#d2531f",
    colorSuccess: "#4d7c4a",
    colorWarning: "#b87d23",
    colorError: "#b83c2b",
    colorInfo: "#4e6e99",
    colorTextBase: "#2b1a12",
    colorBgBase: "#fbf7f4",
    colorPrimaryBg: "#faeee7",
    colorPrimaryBgHover: "#f5ddd0",
    colorPrimaryBorder: "#ebbfa8",
    colorPrimaryBorderHover: "#d2531f",
    colorPrimaryHover: "#b23f12",
    colorPrimaryActive: "#922e0c",
    colorPrimaryText: "#d2531f",
    colorPrimaryTextHover: "#b23f12",
    colorPrimaryTextActive: "#922e0c",
    colorSuccessBg: "#eef5ee",
    colorSuccessBgHover: "#d5e8d6",
    colorSuccessBorder: "#a8ccaa",
    colorSuccessBorderHover: "#4d7c4a",
    colorSuccessHover: "#3e6840",
    colorSuccessActive: "#2d5130",
    colorSuccessText: "#4d7c4a",
    colorSuccessTextHover: "#3e6840",
    colorSuccessTextActive: "#2d5130",
    colorWarningBg: "#faf4e4",
    colorWarningBgHover: "#f2e5c0",
    colorWarningBorder: "#e0c87a",
    colorWarningBorderHover: "#b87d23",
    colorWarningHover: "#a06c1a",
    colorWarningActive: "#8a5c12",
    colorWarningText: "#b87d23",
    colorWarningTextHover: "#a06c1a",
    colorWarningTextActive: "#8a5c12",
    colorErrorBg: "#faeae8",
    colorErrorBgHover: "#f2d0cc",
    colorErrorBorder: "#e0aba6",
    colorErrorBorderHover: "#b83c2b",
    colorErrorHover: "#a03422",
    colorErrorActive: "#892b1a",
    colorErrorText: "#b83c2b",
    colorErrorTextHover: "#a03422",
    colorErrorTextActive: "#892b1a",
    colorInfoBg: "#eaeff7",
    colorInfoBgHover: "#d0dcee",
    colorInfoBorder: "#a0bbdc",
    colorInfoBorderHover: "#4e6e99",
    colorInfoHover: "#3e5c88",
    colorInfoActive: "#2e4c76",
    colorInfoText: "#4e6e99",
    colorInfoTextHover: "#3e5c88",
    colorInfoTextActive: "#2e4c76",
    colorText: "#4a2e20",
    colorTextSecondary: "#6b5347",
    colorTextTertiary: "#9e7c6d",
    colorTextQuaternary: "#cbb5ac",
    colorTextDisabled: "#cbb5ac",
    colorTextPlaceholder: "#8e6e62",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#fdf9f7",
    colorBgLayout: "#f5ebe4",
    colorBgSpotlight: "rgba(43, 26, 18, 0.85)",
    colorBgMask: "rgba(43, 26, 18, 0.45)",
    colorBorder: "#e5d3c6",
    colorBorderSecondary: "#f0e4da",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 2px 8px 0 rgba(43, 26, 18, 0.10)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#ffffff",
      defaultColor: "#4a2e20",
      defaultBorderColor: "#e5d3c6",
      defaultHoverBg: "#fdf6f2",
      defaultHoverColor: "#b23f12",
      defaultHoverBorderColor: "#d2531f",
      defaultActiveBg: "#ffffff",
      defaultActiveColor: "#922e0c",
      defaultActiveBorderColor: "#922e0c"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#ffffff",
      extraColor: "#6b5347"
    },
    Input: {
      hoverBorderColor: "#d2531f",
      activeBorderColor: "#d2531f",
      activeShadow: "0 0 0 1px rgba(210, 83, 31, 0.20)",
      hoverBg: "#ffffff",
      activeBg: "#ffffff"
    },
    Tag: {
      defaultBg: "#faeee7",
      defaultColor: "#d2531f"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#d2531f",
      tailColor: "#e5d3c6"
    },
    Progress: {
      defaultColor: "#d2531f",
      remainingColor: "#f0e4da"
    }
  }
};

export const emberDarkAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#f26b36",
    colorSuccess: "#5c9e5f",
    colorWarning: "#e8aa45",
    colorError: "#d05050",
    colorInfo: "#6895c0",
    colorTextBase: "#f2e6dd",
    colorBgBase: "#1a120e",
    colorPrimaryBg: "#2e1a0e",
    colorPrimaryBgHover: "#3e2414",
    colorPrimaryBorder: "#5e3420",
    colorPrimaryBorderHover: "#f26b36",
    colorPrimaryHover: "#ff824f",
    colorPrimaryActive: "#d45a28",
    colorPrimaryText: "#f2814c",
    colorPrimaryTextHover: "#ff9060",
    colorPrimaryTextActive: "#f26b36",
    colorSuccessBg: "#162214",
    colorSuccessBgHover: "#1e2e1c",
    colorSuccessBorder: "#2e4c2e",
    colorSuccessBorderHover: "#5c9e5f",
    colorSuccessHover: "#70b273",
    colorSuccessActive: "#4a8650",
    colorSuccessText: "#80c884",
    colorSuccessTextHover: "#94d498",
    colorSuccessTextActive: "#5c9e5f",
    colorWarningBg: "#2a1e0a",
    colorWarningBgHover: "#382810",
    colorWarningBorder: "#58401a",
    colorWarningBorderHover: "#e8aa45",
    colorWarningHover: "#f0bc58",
    colorWarningActive: "#c8902e",
    colorWarningText: "#f4c870",
    colorWarningTextHover: "#f8d488",
    colorWarningTextActive: "#e8aa45",
    colorErrorBg: "#2a1412",
    colorErrorBgHover: "#381c1a",
    colorErrorBorder: "#5a2c28",
    colorErrorBorderHover: "#d05050",
    colorErrorHover: "#e06868",
    colorErrorActive: "#b84040",
    colorErrorText: "#e88888",
    colorErrorTextHover: "#f0a0a0",
    colorErrorTextActive: "#d05050",
    colorInfoBg: "#141e2a",
    colorInfoBgHover: "#1a2838",
    colorInfoBorder: "#223a54",
    colorInfoBorderHover: "#6895c0",
    colorInfoHover: "#80aad0",
    colorInfoActive: "#5280aa",
    colorInfoText: "#8bbcd8",
    colorInfoTextHover: "#a0cce8",
    colorInfoTextActive: "#6895c0",
    colorText: "#e8ddd4",
    colorTextSecondary: "#c0a597",
    colorTextTertiary: "#a08070",
    colorTextQuaternary: "#7a6055",
    colorTextDisabled: "#7a6055",
    colorTextPlaceholder: "#b09080",
    colorBgContainer: "#241811",
    colorBgElevated: "#2e2018",
    colorBgLayout: "#140e0a",
    colorBgSpotlight: "rgba(20, 10, 6, 0.92)",
    colorBgMask: "rgba(0, 0, 0, 0.60)",
    colorBorder: "#3e2c21",
    colorBorderSecondary: "#2e2018",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 8px 24px rgba(0, 0, 0, 0.40)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#241811",
      defaultColor: "#e8ddd4",
      defaultBorderColor: "#3e2c21",
      defaultHoverBg: "#2e2018",
      defaultHoverColor: "#f2b45a",
      defaultHoverBorderColor: "#f26b36",
      defaultActiveBg: "#1e1410",
      defaultActiveColor: "#f26b36",
      defaultActiveBorderColor: "#d45a28"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#241811",
      extraColor: "#c0a597"
    },
    Input: {
      hoverBorderColor: "#f26b36",
      activeBorderColor: "#f26b36",
      activeShadow: "0 0 0 1px rgba(242, 107, 54, 0.24)",
      hoverBg: "#1a120e",
      activeBg: "#1a120e"
    },
    Tag: {
      defaultBg: "#2e1a0e",
      defaultColor: "#f2814c"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#f26b36",
      tailColor: "#3e2c21"
    },
    Progress: {
      defaultColor: "#f26b36",
      remainingColor: "#3e2c21"
    }
  }
};

export const mossLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#3e7c41",
    colorSuccess: "#2e6b3a",
    colorWarning: "#9a7e3c",
    colorError: "#b8352a",
    colorInfo: "#45708a",
    colorTextBase: "#1b2a17",
    colorBgBase: "#f6f8f4",
    colorPrimaryBg: "#e8f2e8",
    colorPrimaryBgHover: "#ccdfcc",
    colorPrimaryBorder: "#9ec99f",
    colorPrimaryBorderHover: "#3e7c41",
    colorPrimaryHover: "#2e5f31",
    colorPrimaryActive: "#1f4a22",
    colorPrimaryText: "#3e7c41",
    colorPrimaryTextHover: "#2e5f31",
    colorPrimaryTextActive: "#1f4a22",
    colorSuccessBg: "#e4f0e6",
    colorSuccessBgHover: "#c6e0c8",
    colorSuccessBorder: "#8cbd90",
    colorSuccessBorderHover: "#2e6b3a",
    colorSuccessHover: "#235830",
    colorSuccessActive: "#184424",
    colorSuccessText: "#2e6b3a",
    colorSuccessTextHover: "#235830",
    colorSuccessTextActive: "#184424",
    colorWarningBg: "#f8f4e6",
    colorWarningBgHover: "#f0e6c0",
    colorWarningBorder: "#dcc878",
    colorWarningBorderHover: "#9a7e3c",
    colorWarningHover: "#826832",
    colorWarningActive: "#6c5428",
    colorWarningText: "#9a7e3c",
    colorWarningTextHover: "#826832",
    colorWarningTextActive: "#6c5428",
    colorErrorBg: "#faebe9",
    colorErrorBgHover: "#f2d0cc",
    colorErrorBorder: "#e0a8a4",
    colorErrorBorderHover: "#b8352a",
    colorErrorHover: "#9e2c22",
    colorErrorActive: "#85231a",
    colorErrorText: "#b8352a",
    colorErrorTextHover: "#9e2c22",
    colorErrorTextActive: "#85231a",
    colorInfoBg: "#e8eff5",
    colorInfoBgHover: "#ccddea",
    colorInfoBorder: "#8ab0c8",
    colorInfoBorderHover: "#45708a",
    colorInfoHover: "#375e78",
    colorInfoActive: "#2a4e66",
    colorInfoText: "#45708a",
    colorInfoTextHover: "#375e78",
    colorInfoTextActive: "#2a4e66",
    colorText: "#2d4428",
    colorTextSecondary: "#4f6146",
    colorTextTertiary: "#8a9e7e",
    colorTextQuaternary: "#b8ccb0",
    colorTextDisabled: "#b8ccb0",
    colorTextPlaceholder: "#728462",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#fbfdf9",
    colorBgLayout: "#eaf0e4",
    colorBgSpotlight: "rgba(27, 42, 23, 0.85)",
    colorBgMask: "rgba(27, 42, 23, 0.45)",
    colorBorder: "#d2dec7",
    colorBorderSecondary: "#e6eede",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 2px 8px 0 rgba(27, 42, 23, 0.10)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#ffffff",
      defaultColor: "#2d4428",
      defaultBorderColor: "#d2dec7",
      defaultHoverBg: "#f6faf5",
      defaultHoverColor: "#2e5f31",
      defaultHoverBorderColor: "#3e7c41",
      defaultActiveBg: "#ffffff",
      defaultActiveColor: "#1f4a22",
      defaultActiveBorderColor: "#1f4a22"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#ffffff",
      extraColor: "#4f6146"
    },
    Input: {
      hoverBorderColor: "#3e7c41",
      activeBorderColor: "#3e7c41",
      activeShadow: "0 0 0 1px rgba(62, 124, 65, 0.20)",
      hoverBg: "#ffffff",
      activeBg: "#ffffff"
    },
    Tag: {
      defaultBg: "#e8f2e8",
      defaultColor: "#3e7c41"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#3e7c41",
      tailColor: "#d2dec7"
    },
    Progress: {
      defaultColor: "#3e7c41",
      remainingColor: "#e6eede"
    }
  }
};

export const mossDarkAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#5da35f",
    colorSuccess: "#4a9452",
    colorWarning: "#c8a85a",
    colorError: "#c85a55",
    colorInfo: "#6ba0bc",
    colorTextBase: "#e4eee2",
    colorBgBase: "#0f1710",
    colorPrimaryBg: "#152018",
    colorPrimaryBgHover: "#1c2c1e",
    colorPrimaryBorder: "#2c4a30",
    colorPrimaryBorderHover: "#5da35f",
    colorPrimaryHover: "#74be76",
    colorPrimaryActive: "#4a8a4c",
    colorPrimaryText: "#72b874",
    colorPrimaryTextHover: "#88c88a",
    colorPrimaryTextActive: "#5da35f",
    colorSuccessBg: "#132018",
    colorSuccessBgHover: "#1a2c20",
    colorSuccessBorder: "#2a4830",
    colorSuccessBorderHover: "#4a9452",
    colorSuccessHover: "#5eaa66",
    colorSuccessActive: "#3a7a44",
    colorSuccessText: "#6cbe74",
    colorSuccessTextHover: "#82cc88",
    colorSuccessTextActive: "#4a9452",
    colorWarningBg: "#22200a",
    colorWarningBgHover: "#302e0e",
    colorWarningBorder: "#4a4418",
    colorWarningBorderHover: "#c8a85a",
    colorWarningHover: "#d8bc6c",
    colorWarningActive: "#a88840",
    colorWarningText: "#e0cc80",
    colorWarningTextHover: "#e8d898",
    colorWarningTextActive: "#c8a85a",
    colorErrorBg: "#281414",
    colorErrorBgHover: "#341c1c",
    colorErrorBorder: "#543030",
    colorErrorBorderHover: "#c85a55",
    colorErrorHover: "#d87270",
    colorErrorActive: "#b04848",
    colorErrorText: "#e09090",
    colorErrorTextHover: "#e8a4a4",
    colorErrorTextActive: "#c85a55",
    colorInfoBg: "#102030",
    colorInfoBgHover: "#162a3c",
    colorInfoBorder: "#204058",
    colorInfoBorderHover: "#6ba0bc",
    colorInfoHover: "#82b4cc",
    colorInfoActive: "#5288a4",
    colorInfoText: "#90bcd0",
    colorInfoTextHover: "#a4ccde",
    colorInfoTextActive: "#6ba0bc",
    colorText: "#d4e8d0",
    colorTextSecondary: "#a0b49e",
    colorTextTertiary: "#7a9878",
    colorTextQuaternary: "#567855",
    colorTextDisabled: "#567855",
    colorTextPlaceholder: "#90aa8e",
    colorBgContainer: "#17231a",
    colorBgElevated: "#1f2e22",
    colorBgLayout: "#0c140e",
    colorBgSpotlight: "rgba(10, 18, 10, 0.92)",
    colorBgMask: "rgba(0, 0, 0, 0.60)",
    colorBorder: "#2c3e30",
    colorBorderSecondary: "#1f2e22",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 8px 24px rgba(0, 0, 0, 0.40)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#17231a",
      defaultColor: "#d4e8d0",
      defaultBorderColor: "#2c3e30",
      defaultHoverBg: "#1e2e22",
      defaultHoverColor: "#c8a85a",
      defaultHoverBorderColor: "#5da35f",
      defaultActiveBg: "#131e16",
      defaultActiveColor: "#5da35f",
      defaultActiveBorderColor: "#4a8a4c"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#17231a",
      extraColor: "#a0b49e"
    },
    Input: {
      hoverBorderColor: "#5da35f",
      activeBorderColor: "#5da35f",
      activeShadow: "0 0 0 1px rgba(93, 163, 95, 0.24)",
      hoverBg: "#0f1710",
      activeBg: "#0f1710"
    },
    Tag: {
      defaultBg: "#152018",
      defaultColor: "#72b874"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#5da35f",
      tailColor: "#2c3e30"
    },
    Progress: {
      defaultColor: "#5da35f",
      remainingColor: "#2c3e30"
    }
  }
};

export const graphiteLightAntdTheme: ThemeConfig = {
  algorithm: antTheme.defaultAlgorithm,
  token: {
    colorPrimary: "#2f6feb",
    colorSuccess: "#2d7a54",
    colorWarning: "#8a7318",
    colorError: "#be3b3b",
    colorInfo: "#2f6feb",
    colorTextBase: "#1a1d21",
    colorBgBase: "#f7f8f9",
    colorPrimaryBg: "#e8f0fd",
    colorPrimaryBgHover: "#ccdaf8",
    colorPrimaryBorder: "#9cbaf2",
    colorPrimaryBorderHover: "#2f6feb",
    colorPrimaryHover: "#1f56c7",
    colorPrimaryActive: "#1248b0",
    colorPrimaryText: "#2f6feb",
    colorPrimaryTextHover: "#1f56c7",
    colorPrimaryTextActive: "#1248b0",
    colorSuccessBg: "#e6f5ee",
    colorSuccessBgHover: "#c6e6d5",
    colorSuccessBorder: "#8cc4a8",
    colorSuccessBorderHover: "#2d7a54",
    colorSuccessHover: "#226644",
    colorSuccessActive: "#185234",
    colorSuccessText: "#2d7a54",
    colorSuccessTextHover: "#226644",
    colorSuccessTextActive: "#185234",
    colorWarningBg: "#f8f5e4",
    colorWarningBgHover: "#f0e7b8",
    colorWarningBorder: "#d8c660",
    colorWarningBorderHover: "#8a7318",
    colorWarningHover: "#726010",
    colorWarningActive: "#5a4c0c",
    colorWarningText: "#8a7318",
    colorWarningTextHover: "#726010",
    colorWarningTextActive: "#5a4c0c",
    colorErrorBg: "#faeae8",
    colorErrorBgHover: "#f2d0cc",
    colorErrorBorder: "#e0a8a4",
    colorErrorBorderHover: "#be3b3b",
    colorErrorHover: "#a83030",
    colorErrorActive: "#922525",
    colorErrorText: "#be3b3b",
    colorErrorTextHover: "#a83030",
    colorErrorTextActive: "#922525",
    colorInfoBg: "#e8f0fd",
    colorInfoBgHover: "#ccdaf8",
    colorInfoBorder: "#9cbaf2",
    colorInfoBorderHover: "#2f6feb",
    colorInfoHover: "#1f56c7",
    colorInfoActive: "#1248b0",
    colorInfoText: "#2f6feb",
    colorInfoTextHover: "#1f56c7",
    colorInfoTextActive: "#1248b0",
    colorText: "#2e3238",
    colorTextSecondary: "#5b636b",
    colorTextTertiary: "#8e969e",
    colorTextQuaternary: "#c0c6cc",
    colorTextDisabled: "#c0c6cc",
    colorTextPlaceholder: "#7a8490",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#fafbfc",
    colorBgLayout: "#eef0f2",
    colorBgSpotlight: "rgba(26, 29, 33, 0.85)",
    colorBgMask: "rgba(26, 29, 33, 0.45)",
    colorBorder: "#dadde1",
    colorBorderSecondary: "#eceef1",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 2px 8px 0 rgba(26, 29, 33, 0.10)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#ffffff",
      defaultColor: "#2e3238",
      defaultBorderColor: "#dadde1",
      defaultHoverBg: "#f7f8f9",
      defaultHoverColor: "#1f56c7",
      defaultHoverBorderColor: "#2f6feb",
      defaultActiveBg: "#ffffff",
      defaultActiveColor: "#1248b0",
      defaultActiveBorderColor: "#1248b0"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#ffffff",
      extraColor: "#5b636b"
    },
    Input: {
      hoverBorderColor: "#2f6feb",
      activeBorderColor: "#2f6feb",
      activeShadow: "0 0 0 1px rgba(47, 111, 235, 0.20)",
      hoverBg: "#ffffff",
      activeBg: "#ffffff"
    },
    Tag: {
      defaultBg: "#e8f0fd",
      defaultColor: "#2f6feb"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#2f6feb",
      tailColor: "#dadde1"
    },
    Progress: {
      defaultColor: "#2f6feb",
      remainingColor: "#eceef1"
    }
  }
};

export const graphiteDarkAntdTheme: ThemeConfig = {
  algorithm: antTheme.darkAlgorithm,
  token: {
    colorPrimary: "#4d8dff",
    colorSuccess: "#4ba870",
    colorWarning: "#b89a3a",
    colorError: "#d06060",
    colorInfo: "#4d8dff",
    colorTextBase: "#e6e9ed",
    colorBgBase: "#0e1013",
    colorPrimaryBg: "#101a2e",
    colorPrimaryBgHover: "#152440",
    colorPrimaryBorder: "#203b6e",
    colorPrimaryBorderHover: "#4d8dff",
    colorPrimaryHover: "#6fa3ff",
    colorPrimaryActive: "#3870d4",
    colorPrimaryText: "#6fa3ff",
    colorPrimaryTextHover: "#88b5ff",
    colorPrimaryTextActive: "#4d8dff",
    colorSuccessBg: "#102018",
    colorSuccessBgHover: "#162c22",
    colorSuccessBorder: "#224a34",
    colorSuccessBorderHover: "#4ba870",
    colorSuccessHover: "#60bc85",
    colorSuccessActive: "#3a8e5c",
    colorSuccessText: "#72cc94",
    colorSuccessTextHover: "#88d8a8",
    colorSuccessTextActive: "#4ba870",
    colorWarningBg: "#201c0a",
    colorWarningBgHover: "#2e280e",
    colorWarningBorder: "#4a4018",
    colorWarningBorderHover: "#b89a3a",
    colorWarningHover: "#ccae4c",
    colorWarningActive: "#987e28",
    colorWarningText: "#d4be60",
    colorWarningTextHover: "#e0cc7a",
    colorWarningTextActive: "#b89a3a",
    colorErrorBg: "#281010",
    colorErrorBgHover: "#381818",
    colorErrorBorder: "#5a2828",
    colorErrorBorderHover: "#d06060",
    colorErrorHover: "#e07878",
    colorErrorActive: "#b84848",
    colorErrorText: "#e89090",
    colorErrorTextHover: "#f0a4a4",
    colorErrorTextActive: "#d06060",
    colorInfoBg: "#101a2e",
    colorInfoBgHover: "#152440",
    colorInfoBorder: "#203b6e",
    colorInfoBorderHover: "#4d8dff",
    colorInfoHover: "#6fa3ff",
    colorInfoActive: "#3870d4",
    colorInfoText: "#6fa3ff",
    colorInfoTextHover: "#88b5ff",
    colorInfoTextActive: "#4d8dff",
    colorText: "#d8dce2",
    colorTextSecondary: "#9aa2ab",
    colorTextTertiary: "#72787e",
    colorTextQuaternary: "#50565e",
    colorTextDisabled: "#50565e",
    colorTextPlaceholder: "#848c95",
    colorBgContainer: "#171a1f",
    colorBgElevated: "#20242b",
    colorBgLayout: "#0a0d10",
    colorBgSpotlight: "rgba(8, 10, 14, 0.92)",
    colorBgMask: "rgba(0, 0, 0, 0.60)",
    colorBorder: "#2f353d",
    colorBorderSecondary: "#20242b",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 5,
    borderRadiusLG: 12,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow: "none",
    boxShadowSecondary: "0 8px 24px rgba(0, 0, 0, 0.40)"
  },
  components: {
    ...sharedComponents,
    Button: {
      ...sharedComponents?.Button,
      defaultBg: "#171a1f",
      defaultColor: "#d8dce2",
      defaultBorderColor: "#2f353d",
      defaultHoverBg: "#1e2228",
      defaultHoverColor: "#6fa3ff",
      defaultHoverBorderColor: "#4d8dff",
      defaultActiveBg: "#141720",
      defaultActiveColor: "#4d8dff",
      defaultActiveBorderColor: "#3870d4"
    },
    Card: {
      ...sharedComponents?.Card,
      headerBg: "#171a1f",
      extraColor: "#9aa2ab"
    },
    Input: {
      hoverBorderColor: "#4d8dff",
      activeBorderColor: "#4d8dff",
      activeShadow: "0 0 0 1px rgba(77, 141, 255, 0.24)",
      hoverBg: "#0e1013",
      activeBg: "#0e1013"
    },
    Tag: {
      defaultBg: "#101a2e",
      defaultColor: "#6fa3ff"
    },
    Timeline: {
      ...sharedComponents?.Timeline,
      dotBg: "#4d8dff",
      tailColor: "#2f353d"
    },
    Progress: {
      defaultColor: "#4d8dff",
      remainingColor: "#2f353d"
    }
  }
};

export const appThemeOptions: Array<{ label: string; value: AppThemeMode }> = [
  { label: "Agentswarm Light", value: "light" },
  { label: "Agentswarm Dark", value: "dark" },
  { label: "Forge Light", value: "forge-light" },
  { label: "Forge Dark", value: "forge" },
  { label: "Github Light", value: "github-light" },
  { label: "Github Dark", value: "github" },
  { label: "Verft Light", value: "verft-light" },
  { label: "Verft Dark", value: "verft-dark" },
  { label: "Ember Light", value: "ember-light" },
  { label: "Ember Dark", value: "ember-dark" },
  { label: "Moss Light", value: "moss-light" },
  { label: "Moss Dark", value: "moss-dark" },
  { label: "Graphite Light", value: "graphite-light" },
  { label: "Graphite Dark", value: "graphite-dark" }
];

export const isDarkAppTheme = (mode: AppThemeMode): boolean =>
  mode === "dark" ||
  mode === "forge" ||
  mode === "github" ||
  mode === "verft-dark" ||
  mode === "ember-dark" ||
  mode === "moss-dark" ||
  mode === "graphite-dark";

export const getAppAntdTheme = (mode: AppThemeMode): ThemeConfig => {
  switch (mode) {
    case "dark":
      return darkAntdTheme;
    case "forge":
      return forgeAntdTheme;
    case "forge-light":
      return forgeLightAntdTheme;
    case "github":
      return githubAntdTheme;
    case "github-light":
      return githubLightAntdTheme;
    case "verft-light":
      return verftLightAntdTheme;
    case "verft-dark":
      return verftDarkAntdTheme;
    case "ember-light":
      return emberLightAntdTheme;
    case "ember-dark":
      return emberDarkAntdTheme;
    case "moss-light":
      return mossLightAntdTheme;
    case "moss-dark":
      return mossDarkAntdTheme;
    case "graphite-light":
      return graphiteLightAntdTheme;
    case "graphite-dark":
      return graphiteDarkAntdTheme;
    default:
      return lightAntdTheme;
  }
};
